### ISSUE TITLE
Feature Request: Required configuration settings

### ISSUE THREAD

**Issue by icy-arctic-fox** [piotrmurach/tty-config#10]
A useful feature would be to specify which configuration settings are required. If the setting is missing, an error is raised on retrieval or on read.

Currently, I use:
```ruby
config.fetch(:email) { raise "Missing required email field" }
```

Maybe something like this?
```ruby
config.required(:email)
```

**Comment by piotrmurach** [comment]
Hi Michael,

Thanks for using this gem! 

I'm not sure this is something that should be included. I wish to keep things minimal. Validation logic is best kept outside of the library. 

I also wonder if this is a good thing to be checking for a value when you're fetching/reading it. Probably, it's best if your application checks/forces the email to be set first. You can further enforce that it is not nil by using [validate](https://github.com/piotrmurach/tty-config#211-validate). You can also use the `block` form so that the value is checked on read.

```ruby
config.validate(:email) do |key, val|
  raise "BOOM" if val.nil?
end
config.set(:email) { nil } # delayed evaluation
config.fetch(:email) # => raises "BOOM"
```

**Comment by icy-arctic-fox** [comment]
That's understandable. I don't think validation should be in the gem either, since that's up to the user's requirements. I figured it might be useful to have a short way to specify that a field is required. For multiple required fields, it gets boilerplatey to repeat raising exceptions.

I was unaware that you could use `#validate` for fields that aren't set. I thought it only checked the field if it was present. If that's the case, then I can probably rewrite some of my code.
